In [ ]:
import pandas as pd
import numpy as np

In [ ]:
entries = {'swift': 64900,
           'santro': '391000',
           'audi': 5476000,
           'elantra': 1786000,
           'bolero': 1091000 }
car_series = pd . Series (data = entries, name = 'price')
print (car_series)

swift        64900
santro      391000
audi       5476000
elantra    1786000
bolero     1091000
Name: price, dtype: object

In [ ]:
type(car_series['santro'])

str

In [ ]:
len(car_series)

5

In [ ]:
car_series.shape

(5,)

In [ ]:
entries = {'swift': 64900,
           'santro': 391000,
           'audi': 5476000,
           'elantra': 1786000,
           'bolero': 1091000 }
car_series = pd . Series (data = entries, name = 'price')
print (car_series)

swift        64900
santro      391000
audi       5476000
elantra    1786000
bolero     1091000
Name: price, dtype: int64

In [ ]:
car_series>1000000

swift      False
santro     False
audi        True
elantra     True
bolero      True
Name: price, dtype: bool

In [ ]:
car_series[car_series>1000000]

audi       5476000
elantra    1786000
bolero     1091000
Name: price, dtype: int64

In [ ]:
car_series[car_series>1000000].index[0]

'audi'

In [ ]:
car_series[car_series>1000000].values[0]

np.int64(5476000)

In [ ]:
car_series [(car_series>1000000)&(car_series<2000000)]

elantra    1786000
bolero     1091000
Name: price, dtype: int64

In [ ]:
cust_names = ['hemang', 'farhaan', ' himadri', 'monisha']
cust_bill = [256.78, 454.86,109.00 ,529.89]
cust_ionfo = pd. Series(cust_bill, cust_names)
cust_ionfo

hemang      256.78
farhaan     454.86
 himadri    109.00
monisha     529.89
dtype: float64

In [ ]:
cust_ionfo>300

hemang      False
farhaan      True
 himadri    False
monisha      True
dtype: bool

In [ ]:
cust_ionfo[cust_ionfo>300]

farhaan    454.86
monisha    529.89
dtype: float64

In [ ]:
print (list (cust_ionfo[cust_ionfo>300].index))

['farhaan', 'monisha']

In [ ]:
entries = {'swift': 64900,
           'santro': 391000,
           'audi': 5476000,
           'elantra': 1786000,
           'bolero': 1091000 }
car_series = pd . Series (data = entries, name = 'price')
print (car_series)

swift        64900
santro      391000
audi       5476000
elantra    1786000
bolero     1091000
Name: price, dtype: int64

In [ ]:
car_series.loc[['swift']]

swift    64900
Name: price, dtype: int64

In [ ]:
car_series.loc[['swift','audi']]

swift      64900
audi     5476000
Name: price, dtype: int64

In [ ]:
car_series.loc['swift':'elantra']

swift        64900
santro      391000
audi       5476000
elantra    1786000
Name: price, dtype: int64

In [ ]:
df = pd.DataFrame({
    'product' : ['A', 'B','C'],
    'price': [100, 150, 200],
    'quantity': [5,4,3]
})
print ("\nDataFrame:\n", df)

DataFrame:
   product  price  quantity
0       A    100         5
1       B    150         4
2       C    200         3

In [ ]:
df_csv = pd.DataFrame({
    'product' : ['Soap', 'Soap' ,'Shampoo','Shampoo','Toothpast','Oil'],
    'price': [30, 120,50, 45, 30 ,150],
    'quantity': [100,60,50,80,30,50]
})
df_csv

     product  price  quantity
0       Soap     30       100
1       Soap    120        60
2    Shampoo     50        50
3    Shampoo     45        80
4  Toothpast     30        30
5        Oil    150        50

In [ ]:
df_csv.to_csv("retail_sales.csv", index = False)

print ("file created successfull")

file created successfull

In [ ]:
sales = pd.read_csv("retail_sales.csv")

print ("\n CSV Data from File\n\n", sales)

 CSV Data from File

      product  price  quantity
0       Soap     30       100
1       Soap    120        60
2    Shampoo     50        50
3    Shampoo     45        80
4  Toothpast     30        30
5        Oil    150        50

In [ ]:
sales['price']

0     30
1    120
2     50
3     45
4     30
5    150
Name: price, dtype: int64

In [ ]:
sales[['price', 'quantity']]

   price  quantity
0     30       100
1    120        60
2     50        50
3     45        80
4     30        30
5    150        50

In [ ]:
sales.loc[:,'product':'quantity']

     product  price  quantity
0       Soap     30       100
1       Soap    120        60
2    Shampoo     50        50
3    Shampoo     45        80
4  Toothpast     30        30
5        Oil    150        50

# Aggregations (groupby, mean)
## Concept 
### Groupby: 
Split data into groups based on criteria
### Aggrigation:
Compute statistics (mean, sum) for each group

In [ ]:
sales_group = sales.groupby('quantity')
print (sales_group ['price'].mean())

quantity
30      30.0
50     100.0
60     120.0
80      45.0
100     30.0
Name: price, dtype: float64

In [ ]:
sales_group = sales.groupby('quantity')
print (sales_group ['price'].sum())

quantity
30      30
50     200
60     120
80      45
100     30
Name: price, dtype: int64

In [ ]:
sales_group = sales.groupby('quantity')
print (sales_group['price'].max())

quantity
30      30
50     150
60     120
80      45
100     30
Name: price, dtype: int64

In [ ]:
sales.groupby('quantity')['price'].max()

quantity
30      30
50     150
60     120
80      45
100     30
Name: price, dtype: int64

In [ ]:
df = pd.read_csv("retail_sales.csv")
df.head(6)

     product  price  quantity
0       Soap     30       100
1       Soap    120        60
2    Shampoo     50        50
3    Shampoo     45        80
4  Toothpast     30        30
5        Oil    150        50

In [ ]:
sales.groupby('product').max()

           price  quantity
product
Oil          150        50
Shampoo       50        80
Soap         120       100
Toothpast     30        30

# Sorting with Pandas
## Concept 
sort_values(): Order data by cloumn values

key parameters: by (column), ascending (True/False)

In [ ]:
sorted_sales = sales.sort_values(by='quantity', ascending= False)
sorted_sales

     product  price  quantity
0       Soap     30       100
3    Shampoo     45        80
1       Soap    120        60
2    Shampoo     50        50
5        Oil    150        50
4  Toothpast     30        30

In [ ]:
sorted_sales = sales.sort_values(by='quantity', ascending= True)
sorted_sales

     product  price  quantity
4  Toothpast     30        30
2    Shampoo     50        50
5        Oil    150        50
1       Soap    120        60
3    Shampoo     45        80
0       Soap     30       100

In [ ]:
print (sorted_sales[['price','product']].head())

   price  product
0     30     Soap
3     45  Shampoo
1    120     Soap
2     50  Shampoo
5    150      Oil

**Summary Cheat Sheet**

| Task | Code Example |
| --- | --- |
| Find missing values | `df.isnull().sum()` |
| Fill with mean | `df['col'].fillna(df['col'].mean())` |
| Group by & mean | `df.groupby('col')['target'].mean()` |
| Sort values | `df.sort_values(by='col', ascending=False)` |

In [ ]:
df = pd.read_csv('encounters.csv')
print ("first 5 rows of the data set") 
df.head()

first 5 rows of the data set

,Id,START,STOP,PATIENT,ORGANIZATION,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
0,32c84703-2481-49cd-d571-3899d5820253,2011-01-02T09:26:36Z,2011-01-02T12:58:36Z,3de74169-7f67-9304-91d4-757e0f3a14d2,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,ambulatory,185347001,Encounter for problem (procedure),85.55,1018.02,0.00,NaN,NaN
1,c98059da-320a-c0a6-fced-c8815f3e3f39,2011-01-03T05:44:39Z,2011-01-03T06:01:42Z,d9ec2e44-32e9-9148-179a-1653348cc4e2,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,outpatient,308335008,Patient encounter procedure,142.58,2619.36,0.00,NaN,NaN
2,4ad28a3a-2479-782b-f29c-d5b3f41a001e,2011-01-03T14:32:11Z,2011-01-03T14:47:11Z,73babadf-5b2b-fee7-189e-6f41ff213e01,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185349003,Encounter for check up (procedure),85.55,461.59,305.27,NaN,NaN
3,c3f4da61-e4b4-21d5-587a-fbc89943bc19,2011-01-03T16:24:45Z,2011-01-03T16:39:45Z,3b46a0b7-0f34-9b9a-c319-ace4a1f58c0b,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,wellness,162673000,General examination of patient (procedure),136.80,1784.24,0.00,NaN,NaN
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,2011-01-03T17:36:53Z,2011-01-03T17:51:53Z,fa006887-d93c-d302-8b89-f3c25f88c0e1,d78e84ec-30aa-3bba-a33a-f29a3a454662,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,ambulatory,390906007,Follow-up encounter,85.55,234.72,0.00,55822004.0,Hyperlipidemia

In [ ]:
df.tail()

,Id,START,STOP,PATIENT,ORGANIZATION,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
27886,917bb534-2ed3-e1f5-ac27-74f314d19c63,2022-01-29T11:42:06Z,2022-01-29T11:57:06Z,0c122290-8c15-77ac-b418-2fea4e8a8e6a,d78e84ec-30aa-3bba-a33a-f29a3a454662,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,outpatient,185349003,Encounter for check up (procedure),85.55,85.55,24.27,NaN,NaN
27887,07710480-9d6b-9c9b-87c3-c1d54df4069d,2022-01-29T20:12:53Z,2022-01-29T20:27:53Z,20a4bc24-6b69-2f5c-dc74-1df390cae25b,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,urgentcare,702927004,Urgent care clinic (procedure),142.58,10588.34,8438.67,NaN,NaN
27888,01b57f06-cebe-a3e4-4423-a796ffb0c35d,2022-01-29T20:35:37Z,2022-01-29T20:50:37Z,ff1b3c26-53a6-4590-ce79-a3f7269274ea,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,ambulatory,424619006,Prenatal visit,142.58,11984.29,0.00,72892002.0,Normal pregnancy
27889,7d435668-0813-eb3b-0f26-cb741fb39561,2022-01-29T20:35:37Z,2022-01-29T20:50:37Z,ff1b3c26-53a6-4590-ce79-a3f7269274ea,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,wellness,162673000,General examination of patient (procedure),136.80,408.80,0.00,NaN,NaN
27890,64dfd3ce-7123-fa23-ec24-f74b492553e2,2022-02-05T20:27:36Z,2022-02-05T20:42:36Z,e2d8e1ed-6f63-54e2-d14e-8346799e92ef,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,wellness,308646001,Death Certification,136.80,0.00,0.00,88805009.0,Chronic congestive heart failure (disorder)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27891 entries, 0 to 27890
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   27891 non-null  str
 1   START                27891 non-null  str
 2   STOP                 27891 non-null  str
 3   PATIENT              27891 non-null  str
 4   ORGANIZATION         27891 non-null  str
 5   PAYER                27891 non-null  str
 6   ENCOUNTERCLASS       27891 non-null  str
 7   CODE                 27891 non-null  int64
 8   DESCRIPTION          27891 non-null  str
 9   BASE_ENCOUNTER_COST  27891 non-null  float64
 10  TOTAL_CLAIM_COST     27891 non-null  float64
 11  PAYER_COVERAGE       27891 non-null  float64
 12  REASONCODE           8350 non-null   float64
 13  REASONDESCRIPTION    8350 non-null   str
dtypes: float64(4), int64(1), str(9)
memory usage: 3.0 MB

In [ ]:
possible_cols = ['ID','PATIENT', 'ENCOUNTERCLASS', 'BASE_ENCOUNTER_COST','PAYER','REASONDESCRIPTION']

In [ ]:
print ("\n missing values in the column:\n")
df.isnull().sum()

 missing values in the column:

Id                         0
START                      0
STOP                       0
PATIENT                    0
ORGANIZATION               0
PAYER                      0
ENCOUNTERCLASS             0
CODE                       0
DESCRIPTION                0
BASE_ENCOUNTER_COST        0
TOTAL_CLAIM_COST           0
PAYER_COVERAGE             0
REASONCODE             19541
REASONDESCRIPTION      19541
dtype: int64

In [ ]:
# t=df['REASONCODE']
t= df['BASE_ENCOUNTER_COST']
t.tail(20)

27871    142.58
27872     85.55
27873    142.58
27874     85.55
27875    146.18
27876    136.80
27877     85.55
27878     85.55
27879     85.55
27880    142.58
27881     85.55
27882    136.80
27883     85.55
27884    142.58
27885    146.18
27886     85.55
27887    142.58
27888    142.58
27889    136.80
27890    136.80
Name: BASE_ENCOUNTER_COST, dtype: float64

In [ ]:
# df['BASE_ENCOUNTER_COST'].fillna(df[BASE_ENCOUNTER_COST].median(), inplace = True)
df['BASE_ENCOUNTER_COST']

0         85.55
1        142.58
2         85.55
3        136.80
4         85.55
          ...
27886     85.55
27887    142.58
27888    142.58
27889    136.80
27890    136.80
Name: BASE_ENCOUNTER_COST, Length: 27891, dtype: float64

In [ ]:
df.dropna(subset=['REASONDESCRIPTION'], inplace = True)
print ("\n After handelling missing values")
df.head()

 After handelling missing values

,Id,START,STOP,PATIENT,ORGANIZATION,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,2011-01-03T17:36:53Z,2011-01-03T17:51:53Z,fa006887-d93c-d302-8b89-f3c25f88c0e1,d78e84ec-30aa-3bba-a33a-f29a3a454662,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,ambulatory,390906007,Follow-up encounter,85.55,234.72,0.00,55822004.0,Hyperlipidemia
7,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,2011-01-04T14:49:55Z,2011-01-04T15:04:55Z,d856d6e6-4c98-e7a2-129b-44076c63d008,d78e84ec-30aa-3bba-a33a-f29a3a454662,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,ambulatory,185347001,Encounter for problem,85.55,11855.19,11205.43,363406005.0,Malignant tumor of colon
9,17966936-0878-f4db-128b-a43ae10d0878,2011-01-05T04:02:09Z,2011-01-05T04:17:09Z,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185347001,Encounter for problem,85.55,9881.17,7872.94,254637007.0,Non-small cell lung cancer (disorder)
14,4b6a38e6-7df9-2d75-d850-6bd662f3d05b,2011-01-07T21:02:09Z,2011-01-07T22:39:45Z,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185347001,Encounter for problem,85.55,5136.00,4076.80,424132000.0,Non-small cell carcinoma of lung TNM stage 1 ...
16,f39e72a6-a58e-0aea-cc1f-8aee6f126cc0,2011-01-08T15:20:55Z,2011-01-08T15:35:55Z,88986fec-6364-262e-37d4-e20ceb511166,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,ambulatory,390906007,Follow-up encounter,85.55,234.72,155.77,55822004.0,Hyperlipidemia

In [ ]:
df.info()

<class 'pandas.DataFrame'>
Index: 8350 entries, 4 to 27890
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   8350 non-null   str
 1   START                8350 non-null   str
 2   STOP                 8350 non-null   str
 3   PATIENT              8350 non-null   str
 4   ORGANIZATION         8350 non-null   str
 5   PAYER                8350 non-null   str
 6   ENCOUNTERCLASS       8350 non-null   str
 7   CODE                 8350 non-null   int64
 8   DESCRIPTION          8350 non-null   str
 9   BASE_ENCOUNTER_COST  8350 non-null   float64
 10  TOTAL_CLAIM_COST     8350 non-null   float64
 11  PAYER_COVERAGE       8350 non-null   float64
 12  REASONCODE           8350 non-null   float64
 13  REASONDESCRIPTION    8350 non-null   str
dtypes: float64(4), int64(1), str(9)
memory usage: 978.5 KB

## Average of column name base encounter cost for encounter column

In [ ]:
avg = df.groupby('ENCOUNTERCLASS')['BASE_ENCOUNTER_COST'].mean()
print(avg)

ENCOUNTERCLASS
ambulatory    110.034084
emergency     139.201323
inpatient     135.808129
outpatient     85.550000
wellness      136.800000
Name: BASE_ENCOUNTER_COST, dtype: float64

 ## Grouping for TOTEL_CLAIM_COST by PAYER

In [ ]:
grp = df.groupby('PAYER')['TOTAL_CLAIM_COST'].sum()
print(grp)

PAYER
047f6ec3-6215-35eb-9608-f9dda363a44c    1195513.62
42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a    1700220.24
4d71f845-a6a9-3c39-b242-14d25ef86a8d    1091943.15
5059a55e-5d6e-34d1-b6cb-d83d16e57bcf    1051841.75
6e2f1a2d-27bd-3701-8d08-dae202c58632    1623290.20
7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a    7165889.64
7caa7254-5050-3b5e-9eae-bd5ea30e809c    2828182.83
b1c428d6-4f07-31e0-90f0-68ffa6ff8c76    9983932.33
b3221cfc-24fb-339e-823d-bc4136cbc4ed     534523.99
d47b3510-2895-3b70-9897-342d681c769d    1354417.07
Name: TOTAL_CLAIM_COST, dtype: float64

# Sorting, Mering , Apply

In [ ]:
df.head()

,Id,START,STOP,PATIENT,ORGANIZATION,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,2011-01-03T17:36:53Z,2011-01-03T17:51:53Z,fa006887-d93c-d302-8b89-f3c25f88c0e1,d78e84ec-30aa-3bba-a33a-f29a3a454662,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,ambulatory,390906007,Follow-up encounter,85.55,234.72,0.00,55822004.0,Hyperlipidemia
7,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,2011-01-04T14:49:55Z,2011-01-04T15:04:55Z,d856d6e6-4c98-e7a2-129b-44076c63d008,d78e84ec-30aa-3bba-a33a-f29a3a454662,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,ambulatory,185347001,Encounter for problem,85.55,11855.19,11205.43,363406005.0,Malignant tumor of colon
9,17966936-0878-f4db-128b-a43ae10d0878,2011-01-05T04:02:09Z,2011-01-05T04:17:09Z,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185347001,Encounter for problem,85.55,9881.17,7872.94,254637007.0,Non-small cell lung cancer (disorder)
14,4b6a38e6-7df9-2d75-d850-6bd662f3d05b,2011-01-07T21:02:09Z,2011-01-07T22:39:45Z,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185347001,Encounter for problem,85.55,5136.00,4076.80,424132000.0,Non-small cell carcinoma of lung TNM stage 1 ...
16,f39e72a6-a58e-0aea-cc1f-8aee6f126cc0,2011-01-08T15:20:55Z,2011-01-08T15:35:55Z,88986fec-6364-262e-37d4-e20ceb511166,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,ambulatory,390906007,Follow-up encounter,85.55,234.72,155.77,55822004.0,Hyperlipidemia

In [ ]:
sort = df.sort_values(by='BASE_ENCOUNTER_COST', ascending=False)
print ("\n top 5 most expensive encounters: \n")
sort[['Id','BASE_ENCOUNTER_COST']].head()

 top 5 most expensive encounters:

                                         Id  BASE_ENCOUNTER_COST
95     7929bcef-0b8c-cbc9-83fd-dbaf57400f7d               146.18
13550  595809db-e889-3b91-26f1-8ff44e87f71c               146.18
13635  db23cdf6-4ae1-0413-6fea-f40cf5f70787               146.18
13633  87d077d7-41cc-16e0-ae35-bf142060f2ea               146.18
15051  b422dab9-9801-64ed-0124-10a219d1ac5c               146.18

In [ ]:
df.head()

,Id,START,STOP,PATIENT,ORGANIZATION,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,2011-01-03T17:36:53Z,2011-01-03T17:51:53Z,fa006887-d93c-d302-8b89-f3c25f88c0e1,d78e84ec-30aa-3bba-a33a-f29a3a454662,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,ambulatory,390906007,Follow-up encounter,85.55,234.72,0.00,55822004.0,Hyperlipidemia
7,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,2011-01-04T14:49:55Z,2011-01-04T15:04:55Z,d856d6e6-4c98-e7a2-129b-44076c63d008,d78e84ec-30aa-3bba-a33a-f29a3a454662,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,ambulatory,185347001,Encounter for problem,85.55,11855.19,11205.43,363406005.0,Malignant tumor of colon
9,17966936-0878-f4db-128b-a43ae10d0878,2011-01-05T04:02:09Z,2011-01-05T04:17:09Z,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185347001,Encounter for problem,85.55,9881.17,7872.94,254637007.0,Non-small cell lung cancer (disorder)
14,4b6a38e6-7df9-2d75-d850-6bd662f3d05b,2011-01-07T21:02:09Z,2011-01-07T22:39:45Z,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185347001,Encounter for problem,85.55,5136.00,4076.80,424132000.0,Non-small cell carcinoma of lung TNM stage 1 ...
16,f39e72a6-a58e-0aea-cc1f-8aee6f126cc0,2011-01-08T15:20:55Z,2011-01-08T15:35:55Z,88986fec-6364-262e-37d4-e20ceb511166,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,ambulatory,390906007,Follow-up encounter,85.55,234.72,155.77,55822004.0,Hyperlipidemia

In [ ]:
df.info()

<class 'pandas.DataFrame'>
Index: 8350 entries, 4 to 27890
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   8350 non-null   str
 1   START                8350 non-null   str
 2   STOP                 8350 non-null   str
 3   PATIENT              8350 non-null   str
 4   ORGANIZATION         8350 non-null   str
 5   PAYER                8350 non-null   str
 6   ENCOUNTERCLASS       8350 non-null   str
 7   CODE                 8350 non-null   int64
 8   DESCRIPTION          8350 non-null   str
 9   BASE_ENCOUNTER_COST  8350 non-null   float64
 10  TOTAL_CLAIM_COST     8350 non-null   float64
 11  PAYER_COVERAGE       8350 non-null   float64
 12  REASONCODE           8350 non-null   float64
 13  REASONDESCRIPTION    8350 non-null   str
dtypes: float64(4), int64(1), str(9)
memory usage: 978.5 KB

In [ ]:
q = df['ENCOUNTERCLASS'].info()
q

<class 'pandas.Series'>
Index: 8350 entries, 4 to 27890
Series name: ENCOUNTERCLASS
Non-Null Count  Dtype
--------------  -----
8350 non-null   str
dtypes: str(1)
memory usage: 130.5 KB

In [ ]:
df.head(20)

,Id,START,STOP,PATIENT,ORGANIZATION,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,2011-01-03T17:36:53Z,2011-01-03T17:51:53Z,fa006887-d93c-d302-8b89-f3c25f88c0e1,d78e84ec-30aa-3bba-a33a-f29a3a454662,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,ambulatory,390906007,Follow-up encounter,85.55,234.72,0.00,5.582200e+07,Hyperlipidemia
7,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,2011-01-04T14:49:55Z,2011-01-04T15:04:55Z,d856d6e6-4c98-e7a2-129b-44076c63d008,d78e84ec-30aa-3bba-a33a-f29a3a454662,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,ambulatory,185347001,Encounter for problem,85.55,11855.19,11205.43,3.634060e+08,Malignant tumor of colon
9,17966936-0878-f4db-128b-a43ae10d0878,2011-01-05T04:02:09Z,2011-01-05T04:17:09Z,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185347001,Encounter for problem,85.55,9881.17,7872.94,2.546370e+08,Non-small cell lung cancer (disorder)
14,4b6a38e6-7df9-2d75-d850-6bd662f3d05b,2011-01-07T21:02:09Z,2011-01-07T22:39:45Z,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185347001,Encounter for problem,85.55,5136.00,4076.80,4.241320e+08,Non-small cell carcinoma of lung TNM stage 1 ...
16,f39e72a6-a58e-0aea-cc1f-8aee6f126cc0,2011-01-08T15:20:55Z,2011-01-08T15:35:55Z,88986fec-6364-262e-37d4-e20ceb511166,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,ambulatory,390906007,Follow-up encounter,85.55,234.72,155.77,5.582200e+07,Hyperlipidemia
20,32297044-efcf-4ac9-e05f-ca93645c3a8b,2011-01-09T20:57:51Z,2011-01-09T21:12:51Z,e520953a-ee37-4bf4-1df7-aec4b89fb761,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,ambulatory,185345009,Encounter for symptom,85.55,6668.67,0.00,1.050900e+07,Acute bronchitis (disorder)
25,fe402a82-362b-7b48-41c3-33c0213dae27,2011-01-12T05:15:27Z,2011-01-12T05:30:27Z,587e7054-29d1-8d0e-a9d3-adc00db3441f,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,ambulatory,390906007,Follow-up encounter,85.55,234.72,155.77,5.582200e+07,Hyperlipidemia
29,b9d465ca-3cb8-df48-1e43-57726b67a79d,2011-01-13T00:54:19Z,2011-01-13T01:09:19Z,e0f9b98c-f983-cba1-9095-0e48d10f0195,d78e84ec-30aa-3bba-a33a-f29a3a454662,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,ambulatory,185345009,Encounter for symptom,85.55,85.55,0.00,4.448140e+08,Viral sinusitis (disorder)
31,5c504a86-1804-ed37-53ce-32f3d3318ad5,2011-01-13T15:41:08Z,2011-01-13T15:56:08Z,8fe3348d-477f-541e-96df-bbe5b552104f,d78e84ec-30aa-3bba-a33a-f29a3a454662,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,ambulatory,424619006,Prenatal visit,142.58,13281.55,12560.47,7.289200e+07,Normal pregnancy
33,626e9f00-c818-a96e-df91-14671f7e5eec,2011-01-14T21:56:03Z,2011-01-14T22:11:03Z,a7426d06-9c0a-f05b-c9da-63eefb5c3bd3,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,ambulatory,424619006,Prenatal visit,142.58,1005.38,0.00,1.560730e+08,Fetus with unknown complication
37,4a11829f-afdb-3115-0708-8adc1dbac1cb,2011-01-16T03:40:00Z,2011-01-16T03:56:16Z,a6dc36b3-0ac3-48b1-3088-707e8871a914,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,ambulatory,185345009,Encounter for symptom,85.55,500.55,366.30,1.050900e+07,Acute bronchitis (disorder)
46,cffe517b-7347-fa76-355f-20d92e056275,2011-01-18T20:38:53Z,2011-01-18T20:53:53Z,470e7dd9-9788-57f6-ee81-1e9acb075c1c,d78e84ec-30aa-3bba-a33a-f29a3a454662,4d71f845-a6a9-3c39-b242-14d25ef86a8d,ambulatory,185345009,Encounter for symptom,85.55,3952.18,0.00,1.050900e+07,Acute bronchitis (disorder)
47,fa03ab26-73ae-7097-d802-f114934ee1bc,2011-01-19T16:22:13Z,2011-01-19T16:37:13Z,e3eeac06-7f9d-8e95-5cce-2dea6641f469,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,ambulatory,316744009,Office Visit,85.55,85.55,36.44,2.692900e+07,Alzheimer's disease (disorder)
58,0e06fd4f-0c37-39b0-d76f-1743753bcae0,2011-01-21T23:56:20Z,2011-01-22T00:11:20Z,54889029-0a1e-0b75-5980-1c091dd4bc0e,d78e84ec-30aa-3bba-a33a-f29a3a454662,4d71f845-a6a9-3c39-b242-14d25ef86a8d,ambulatory,390906007,Follow-up encounter,85.55,234.72,0.00,5.582200e+07,Hyperlipidemia
62,914cbd5c-b56a-9ae9-319e-15c719364ffd,2011-01-23T03:42:18Z,2011-01-24T03:42:18Z,a80b1160-93f0-db7e-9f23-04ea6fdddfaf,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,inpatient,185347001,Encounter for problem,87.71,8260.15,0.00,6.781100e+13,Primary small cell malignant neoplasm of lung ...
63,7b04e82c-8fc8-4030-d899-8fec5ce072a3,2011-01-23T13:35:32Z,2011-01-23T13:50:32Z,09acf4d1-62d0-3cb1-f123-fb09dbd28e60,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,ambulatory,390906007,Follow-up encounter,85.55,234.72,155.77,5.582200e+07,Hyperlipidemia
64,9078cc7d-26ca-b1a6-98c2-0dbe6a9b84d2,2011-01-23T14:53:31Z,2011-01-24T14:53:31Z,01274098-150f-8211-6150-29f2a2da266c,d78e84ec-30aa-3bba-a33a-f29a3a454662,b3221cfc-24fb-339e-823d-bc4136cbc4ed,inpatient,305336008,Admission to hospice (procedure),146.18,0.00,0.00,2.692900e+07,Alzheimer's disease (disorder)
72,cfe75234-3857-14c2-e6ff-cfb732a40e96,2011-01-25T18:28:39Z,2011-01-25T18:43:39Z,5bd6c434-6f51-6e53-4d0f-8d3889f377da,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,ambulatory,390906007,Follow-up encounter,85.55,234.72,0.00,5.582200e+07,Hyperlipidemia
78,ea494a46-f561-4e46-efa3-1da580a47058,2011-01-28T07:13:29Z,2011-01-28T07:28:29Z,46d8cf44-3ed3-c7b0-bca7-7f3ffd83b8df,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,ambulatory,316744009,Office Visit,85.55,85.55,36.44,2.692900e+07,Alzheimer's disease (disorder)
85,0921ca49-eb5c-89bb-7651-6df9fc30c61b,2011-01-31T20:09:24Z,2011-01-31T20:24:24Z,0330487c-5d77-02a9-9f11-b3cc01d306cd,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,ambulatory,390906007,Follow-up encounter,85.55,234.72,155.77,5.582200e+07,Hyperlipidemia

## filter all emergency encounters, fill missing claim costs with the mean, and find the average claim cost for emergencies.

In [ ]:
em = df[df['ENCOUNTERCLASS']=='emergency'].copy()
mean = em['TOTAL_CLAIM_COST'].mean()
em.loc[:, 'TOTAL_CLAIM_COST']=em['TOTAL_CLAIM_COST'].fillna(mean)
avg = em['TOTAL_CLAIM_COST'].mean()
print ("\n Average claim cost for emergency is: ", round(avg,2) )

 Average claim cost for emergency is:  5193.45

**Line 1: `em = df[df['ENCOUNTERCLASS']=='emergency'].copy()**`

* **What it does:** Filters the original DataFrame `df` to extract only the rows where the column `'ENCOUNTERCLASS'` has the value `'emergency'`.
* **Details:** `.copy()` creates an independent copy of this filtered data in memory, preventing potential `SettingWithCopyWarning` warnings when you modify `em` later.

---

**Line 2: `mean = em['TOTAL_CLAIM_COST'].mean()**`

* **What it does:** Calculates the average (mean) value of the available numerical values in the `'TOTAL_CLAIM_COST'` column for emergency encounters.
* **Details:** Pandas automatically ignores missing values (`NaN`s) when calculating this initial mean and stores the result in the variable `mean`.

---

**Line 3: `em.loc[:, 'TOTAL_CLAIM_COST'] = em['TOTAL_CLAIM_COST'].fillna(mean)**`

* **What it does:** Fills any missing values (`NaN`) in the `'TOTAL_CLAIM_COST'` column of the `em` DataFrame using the `mean` value calculated in Line 2.
* **Details:** `.fillna(mean)` replaces missing entries with the average value, and `.loc[:, 'TOTAL_CLAIM_COST']` safely assigns those updated values back into the column across all rows (`:`).

---

**Line 4: `avg = em['TOTAL_CLAIM_COST'].mean()**`

* **What it does:** Recalculates the mean of the `'TOTAL_CLAIM_COST'` column after missing values have been filled and assigns it to the variable `avg`.
* **Note:** Since the missing values were replaced precisely with the original mean, `avg` will be identical to `mean`.

---

**Line 5: `print ("\n Average claim cost for emergency is: ", round(avg,2) )**`

* **What it does:** Outputs the result to the console.
* **Details:** `\n` creates a new line before the text, and `round(avg, 2)` rounds the final average cost to 2 decimal places before printing it alongside the label text.

The part **`em.loc[:, 'TOTAL_CLAIM_COST']`** is Pandas syntax used to select and isolate a specific column in a DataFrame using label-based indexing (`.loc`).

Here is the exact breakdown:

* **`em`** — The DataFrame you are targeting.
* **`.loc[...]`** — Stands for "location." It allows you to select subset rows and columns by their labels (names) using the format `.loc[rows, columns]`.
* **`:` (the colon before the comma)** — Refers to **all rows**. A single colon without start or end numbers means "select everything from top to bottom."
* **`,` (the comma)** — Separates the row selection from the column selection.
* **`'TOTAL_CLAIM_COST'` (after the comma)** — Specifies the exact column name you want to access.

---

### Why use `.loc[:, 'col_name']` instead of `em['col_name']`?

While both select the same column, writing **`em.loc[:, 'TOTAL_CLAIM_COST'] = ...`** when making assignments (like filling missing values) explicitly tells Pandas: *"Modify this exact column in place across all rows of the existing DataFrame."*

This prevents Pandas from throwing a **`SettingWithCopyWarning`**, which often happens when assigning values to a filtered slice of a DataFrame.